require('./node_modules/bootstrap/dist/css/bootstrap.min.css');
require('styles.less');
require('bootstrap');
require('font-awesome-webpack');
require('jquery');
require('jquery.easing');
require('creative');
require('jquery.magnific-popup');
require('scrollreveal');
